### ISSUE TITLE
add `--dry-run` flag

### ISSUE THREAD

**Issue by edgimar** [alexpovel/srgn#152]
For a tool that can make in-place modifications to many files, it is important to have a `--dry-run` flag.  This allows one to see what would be changed without actually performing changes.  If this output looks correct, then it can be run "for real".

**Comment by alexpovel** [comment]
Thanks for your report!

Makes sense, such a flag should exist. I'll look into providing it. It's similar in spirit to #149.

In the meantime, you can always not take any action (no replacement etc.), which will enter search mode and print in bold red what was found and would be modified if an action were taken. What's missing is of course showing what the final result looks like.

**Comment by edgimar** [comment]
Another related nicety is something like the `--backup` flag as used in the [rpl](https://manpages.ubuntu.com/manpages/lunar/man1/rpl.1.html) tool, which makes a backup copy of any changed files.

**Comment by alexpovel** [comment]
Thanks for the pointer, hadn't heard of `rpl` before. I imagine `srgn` as a tool to search code primarily, and secondarily to manipulate code, and for that code to be under version control. So `--backup` isn't something I see as required. It looks easy enough to implement though, will take a look.

**Comment by alexpovel** [comment]
Hi @edgimar !

What do you think of the implementation in #156 ? The PR has a screenshot of how it could look like too.

**Comment by edgimar** [comment]
I just saw your PR - looks good.  Thanks!
