### ISSUE TITLE
tests fail when building from tarball due to calling git restore

### ISSUE THREAD

**Issue by lolbinarycat** [alexpovel/srgn#66]
```
---- tests::test_cli_files::case_1 stdout ----
Running: "git" "restore" "tests/files-option/basic-python/in"
thread 'tests::test_cli_files::case_1' panicked at tests/cli.rs:106:24:
Head restoration to not fail: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

i'm working on packaging this for nixpkgs and currently i have to disable the check phase due to this.

maybe check for the existence of .git and skip these unit tests if its not found?  or just refactor it so it copies files to a temporary directory first before mutating them in-place?

**Comment by alexpovel** [comment]
Hi! Thanks for your report. I knew that flaky test would come to bite me. I changed it to what seems like the most robust version, copying to a temporary location as you suggested.

Does this fix your issue?

**Comment by lolbinarycat** [comment]
yep! checkPhase now runs successfully.  thank you!
